name: cw3e_ar-tools
channels:
  - conda-forge
  - defaults  
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - netcdf4
  - xarray
  - cartopy
  - cmocean
  - ipykernel
  - pyyaml
  - cfgrib
  - scipy

